# Generated by Django 4.2.27 on 2026-01-05 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copies', models.IntegerField(default=1)),
                ('print_type', models.CharField(choices=[('color', 'Color'), ('black_white', 'Black & White')], max_length=20)),
                ('side', models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], max_length=20)),
                ('binding', models.CharField(choices=[('none', 'None'), ('spiral', 'Spiral'), ('hard', 'Hard')], default='none', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
