# Generated by Django 4.2.27 on 2026-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_type', models.CharField(choices=[('color', 'Color'), ('black_white', 'Black & White')], max_length=20)),
                ('side', models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], max_length=20)),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=6)),
                ('binding_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
