# Generated by Django 4.2.27 on 2026-01-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='bindingpricing',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_pricings', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('shop', 'print_type', 'side')},
        ),
        migrations.AlterUniqueTogether(
            name='bindingpricing',
            unique_together={('shop', 'binding_type')},
        ),
    ]
