# Generated by Django 4.2.27 on 2026-01-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        ('pricing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindingPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(choices=[('soft', 'Soft Binding'), ('hard', 'Hard Binding'), ('spiral', 'Spiral Binding')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_pricings', to='shops.shop')),
            ],
            options={
                'unique_together': {('shop', 'binding_type')},
            },
        ),
    ]
